# App-level pipeline config for github-pipeline-consumer-poc.
# Inherits defaults from the psf group (groups/psf.yml in the framework repo).

app:
  base: psf
  secops:
    dependency_scanning:
      snyk_cli:
        allow_failure: true
    container_scanning:
      snyk_cli:
        allow_failure: true
    sast:
      gitleaks:
        allow_failure: true
      semgrep:
        allow_failure: true
      sonarqube_web_api:
        allow_failure: true
      cxsast:
        allow_failure: true
      snyk_cli:
        allow_failure: true
    linting:
      hadolint:
        allow_failure: true

aws:
  account_id: "654654533841"
  region: us-east-1
  s3_bucket: pipeline-consumer-poc-artifacts
